#!/usr/bin/env python3
"""
RSA Secure Boot Firmware Upload Script
=====================================

Based on upload_firmware.py, with RSA signing support.

Signs the firmware with the RSA private key before uploading.
The payload sent to the STM32 is:

  [FWUP header (12)] [firmware] [RSA signature] [fw_size footer (4)] [magic marker 0x55667788 (4)]

The signature is appended AFTER the firmware binary so the application
vector table stays at offset 0x00 — Bootloader_JumpToApplication()
needs no changes. The fw_size footer lets the bootloader locate the
signature on boot. The magic marker 0x55667788 marks the end of the
payload (more reliable than scanning for 0xFF, which can appear in firmware).

Usage:
  python upload_firmware_rsa.py

Prerequisites:
  - rsa_keys_32.json generated by: python rsa_sign_demo.py --bits 32
  - pyserial installed: pip install pyserial
"""

import serial
import struct
import time
import sys
import zlib
import hashlib
import json
import os

# ======== CONFIG ========
PORT = "COM8"  # ← THAY BẰNG COM PORT CỦA BẠN
BAUD = 115200
BIN_FILE = r"C:\Users\dinhtuan.cao\STM32CubeIDE\cortexm\STM32H750_Application\Debug\STM32H750_Application.bin"
CHUNK_SIZE = 1024
MAX_FIRMWARE_SIZE = 8 * 1024 * 1024
WAIT_FOR_CHUNK_ACK = True
CHUNK_DELAY_SECONDS = 0.02
BOOT_TIMEOUT_SECONDS = 30
ERASE_TIMEOUT_SECONDS = 120
CRC_TIMEOUT_SECONDS = 120
REBOOT_TIMEOUT_SECONDS = 30

# ======== RSA CONFIG ========
RSA_KEY_FILE = "rsa_keys_32.json"   # Generated by rsa_sign_demo.py
RSA_SIG_SIZE = 4                     # RSA-32 = 4 bytes (must match STM32)


# ======== RSA FUNCTIONS ========

def load_rsa_keys(filename):
    """Load RSA key pair from JSON file (generated by rsa_sign_demo.py)."""
    with open(filename, 'r') as f:
        keys = json.load(f)
    print(f"[*] RSA keys loaded from {filename}")
    print(f"    n = {keys['n']} (0x{keys['n']:08X})")
    print(f"    e = {keys['e']}")
    print(f"    d = {keys['d']} (PRIVATE — used for signing only)")
    return keys


def compute_digest(firmware_data):
    """
    Compute SHA-256, take first 4 bytes as 32-bit digest (big-endian).
    Matches the STM32 verification logic exactly.
    """
    sha256_hash = hashlib.sha256(firmware_data).digest()
    digest_bytes = sha256_hash[:4]
    digest = int.from_bytes(digest_bytes, byteorder='big')
    return digest


def rsa_sign(keys, firmware_data):
    """
    Sign firmware with RSA private key.
    signature = (digest mod n) ^ d mod n
    Returns: signature as big-endian bytes (RSA_SIG_SIZE bytes)
    """
    n = keys['n']
    d = keys['d']

    digest = compute_digest(firmware_data)
    digest_mod = digest % n

    signature = pow(digest_mod, d, n)
    sig_bytes = signature.to_bytes(RSA_SIG_SIZE, byteorder='big')

    print(f"[*] RSA signing:")
    print(f"    SHA-256 first 4 bytes: 0x{digest:08X}")
    print(f"    digest mod n:           {digest_mod}")
    print(f"    signature:              0x{signature:08X}")
    print(f"    signature bytes:        {sig_bytes.hex()}")

    return sig_bytes


# ======== UART HELPER FUNCTIONS ========

def build_firmware_header(payload):
    """Build 12-byte header: [FWUP(4)] [size(4)] [crc32(4)]"""
    firmware_crc = zlib.crc32(payload) & 0xFFFFFFFF
    header = b"FWUP" + struct.pack("<I", len(payload))
    header += struct.pack("<I", firmware_crc)
    return header, firmware_crc


def wait_for_message(ser, expected, timeout):
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        raw_line = ser.readline()
        if not raw_line:
            continue
        line = raw_line.decode("utf-8", errors="replace").strip()
        if line:
            print(f"[STM32] {line}")
        if expected in line:
            return
        if "ERROR:" in line:
            raise RuntimeError(f"Bootloader error: {line}")
    raise TimeoutError(f"Timeout waiting for {expected!r}")


def send_bytes(ser, data):
    if ser.write(data) != len(data):
        raise IOError("Serial short write")
    ser.flush()


def send_cmd(ser, cmd_byte):
    """Send a 1-byte protocol command to the STM32."""
    ser.write(bytes([cmd_byte]))
    ser.flush()


def wait_for_cmd(ser, expected_cmd, timeout=10):
    """
    Read from UART until we receive the expected 1-byte command code.
    Text debug messages are printed but skipped during parsing.
    """
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        byte = ser.read(1)
        if not byte:
            continue

        code = byte[0]

        # Check for error codes (0xB0–0xBF)
        if 0xB0 <= code <= 0xBF:
            raise RuntimeError(f"Bootloader error code: 0x{code:02X}")

        # Check for expected status code (0xA0–0xAF)
        if code == expected_cmd:
            return

        # If it's a printable ASCII character, it's likely a text debug message
        # Read the rest of the line and print it for debugging
        if 0x20 <= code <= 0x7E:
            rest = ser.readline()
            line = chr(code) + rest.decode("utf-8", errors="replace").strip()
            if line:
                print(f"[STM32] {line}")
        else:
            print(f"[STM32] Unknown byte: 0x{code:02X}")

    raise TimeoutError(
        f"Timeout waiting for command 0x{expected_cmd:02X}"
    )


# ======== MAIN ========

try:
    # Read .bin file
    print(f"[*] Reading firmware from: {BIN_FILE}")
    with open(BIN_FILE, 'rb') as f:
        fw_data = f.read()

    if not fw_data:
        raise ValueError("Firmware file is empty")
    if len(fw_data) > MAX_FIRMWARE_SIZE:
        raise ValueError("Firmware exceeds W25Q64 capacity")

    # === RSA SIGNING ===
    print(f"\n[*] RSA Secure Boot — signing firmware...")
    keys = load_rsa_keys(RSA_KEY_FILE)
    sig_bytes = rsa_sign(keys, fw_data)

    # Build fw_size footer (4 bytes, little-endian)
    fw_size_footer = struct.pack("<I", len(fw_data))

    # Build magic marker 0x55667788 (4 bytes, little-endian)
    # Marks end of payload — more reliable than scanning for 0xFF
    payload_end_marker = struct.pack("<I", 0x55667788)

    # Payload = firmware binary + RSA signature + fw_size footer + magic marker
    # (signature at the END — vector table stays at offset 0x00)
    payload = fw_data + sig_bytes + fw_size_footer + payload_end_marker
    print(f"[*] Payload: {len(fw_data)} (fw) + {len(sig_bytes)} (sig) + {len(fw_size_footer)} (footer) + {len(payload_end_marker)} (marker) = {len(payload)} bytes")

    # Build header (CRC32 over the entire payload)
    metadata, expected_crc = build_firmware_header(payload)
    total_chunks = (len(payload) + CHUNK_SIZE - 1) // CHUNK_SIZE

    print(f"[OK] Payload size: {len(payload)} bytes")
    print(f"[OK] Payload CRC32: 0x{expected_crc:08X}")
    print(f"[OK] Number of chunks: {total_chunks}")

    # Connect to UART
    print(f"[*] Connecting to {PORT} @ {BAUD} baud...")
    ser = serial.Serial(PORT, BAUD, timeout=0.25, write_timeout=5)
    ser.reset_input_buffer()
    ser.reset_output_buffer()

    print("[*] Press RESET on the STM32 board now")
    print("[*] Waiting for the bootloader update window...")
    wait_for_message(
        ser,
        "[OK] W25Q64 detected",
        BOOT_TIMEOUT_SECONDS,
    )

    print("[*] Sending CMD_UPDATE_START (0x10)...")
    send_cmd(ser, 0x10)
    # Small delay to let STM32 enter Bootloader_UpdateFirmware() and call
    # HAL_UART_Receive for the 12-byte header. Without this, the header
    # bytes arrive before the STM32 is listening and are lost.
    time.sleep(0.05)

    print("[*] Sending FWUP metadata...")
    send_bytes(ser, metadata)

    print("[*] Waiting for STATUS_UPDATE_READY (0xA0)...")
    wait_for_cmd(ser, 0xA0, ERASE_TIMEOUT_SECONDS)
    time.sleep(0.1)

    print("[*] Starting firmware upload (firmware + signature + footer + marker)...")

    # Send payload in chunks
    bytes_sent = 0
    for i in range(0, len(payload), CHUNK_SIZE):
        chunk = payload[i:i + CHUNK_SIZE]
        chunk_len = len(chunk)

        # Packet = LE16 chunk length followed by raw payload bytes.
        packet = struct.pack('<H', chunk_len) + chunk
        send_bytes(ser, packet)

        if WAIT_FOR_CHUNK_ACK:
            wait_for_cmd(ser, 0xA1, 10)    # STATUS_CHUNK_ACK
        else:
            time.sleep(CHUNK_DELAY_SECONDS)

        bytes_sent += chunk_len
        print(f"[+] Sent {bytes_sent} / {len(payload)} bytes ({100 * bytes_sent / len(payload):.1f}%)")

    # Send end marker (0x00 0x00)
    print("[*] Sending end marker...")
    send_bytes(ser, struct.pack('<H', 0))

    print("[*] Waiting for STATUS_UPDATE_COMPLETE (0xA2)...")
    wait_for_cmd(ser, 0xA2, CRC_TIMEOUT_SECONDS)

    print("[OK] Firmware upload, CRC, and RSA verification complete!")
    print(f"[OK] Verified CRC32: 0x{expected_crc:08X}")

    # Brief delay to let the STM32 send the reboot message (text, optional).
    time.sleep(0.5)

    ser.close()
    print("[SUCCESS] Done!")

except FileNotFoundError:
    print(f"[ERROR] File not found: {BIN_FILE}")
    sys.exit(1)
except serial.SerialException as e:
    print(f"[ERROR] Serial port error: {e}")
    print(f"[TIP] Check Device Manager for correct COM port")
    sys.exit(1)
except (ValueError, RuntimeError, TimeoutError, OSError) as e:
    print(f"[ERROR] {e}")
    sys.exit(1)
except Exception as e:
    print(f"[ERROR] {e}")
    sys.exit(1)
