/*
 * bootloader.h
 *
 *  Created on: Aug 10, 2026
 *      Author: dinhtuan.cao
 */

#ifndef INC_BOOTLOADER_H_
#define INC_BOOTLOADER_H_

#include "external_flash.h"
#include "sha256.h"
#include <stdio.h>

#define BOOT_TEST                (0) /* 1 -> Enable ; 0 -> Disable  */

#define FW_HEADER_SIZE  12U

/* --- Design choice: erase firmware in 64 KB blocks for speed --- */
#define QSPI_FW_ERASE_GRANULARITY  (QSPI_FLASH_BLOCK_SIZE)

#define QSPI_APP_ADDR            (0x00000000)       /* App at flash start */
#define QSPI_APP_MAX_SIZE        (8 * 1024 * 1024)  /* Full 8 MB used for app */
#define CHUNK_SIZE               (1024)             /* Receive buffer size */


/* ==================== Binary Protocol Command Codes ==================== */
/*
 * IMPORTANT: STM32→Host codes use 0xA0+ to avoid collision with printable
 * ASCII text (0x20–0x7E). Without this, code 0x20 (space) would be
 * indistinguishable from the leading space in "  Erased 1 MB".
 *
 * Host→STM32 uses 0x10 (non-printable, DLE) — safe because the STM32 is
 * only listening (not sending text) when it expects this byte.
 */

/* Host → STM32 */
#define CMD_UPDATE_START        0x10U   /* Host requests firmware update     */

/* STM32 → Host (0xA0+ — non-ASCII, never appears in text debug) */
#define STATUS_UPDATE_READY     0xA0U   /* Flash erased, ready for fw data    */
#define STATUS_CHUNK_ACK        0xA1U   /* Chunk received & written OK        */
#define STATUS_UPDATE_COMPLETE  0xA2U   /* CRC verified, update successful    */

/* Error codes (STM32 → Host, 0xB0+ — non-ASCII) */
#define ERROR_GENERIC           0xB0U   /* Unknown error                      */
#define ERROR_HEADER            0xB1U   /* Invalid firmware header            */
#define ERROR_CRC               0xB2U   /* CRC mismatch                       */
#define ERROR_FLASH             0xB3U   /* Flash erase/write failure          */
#define ERROR_CHUNK             0xB4U   /* Invalid chunk (length/timeout)     */
#define ERROR_RSA               0xB5U   /* RSA signature verification failed   */

/* ==================== RSA Secure Boot Configuration ==================== */

/* Enable RSA signature verification (0 = disabled, 1 = enabled) */
#define RSA_SECURE_BOOT_ENABLE   (1)

/* RSA key size in bits (must match the key used by rsa_sign_demo.py) */
#define RSA_KEY_BITS             (32)

/* Signature size in bytes = RSA_KEY_BITS / 8 */
#define RSA_SIG_SIZE             (RSA_KEY_BITS / 8U)

/*
 * RSA-32 Public Key — generated by: python rsa_sign_demo.py --bits 32
 *
 * Replace these values with the output from your own key generation.
 * The private exponent d is NEVER embedded in the device.
 *
 * Example (from demo output):
 *   n = 0xB618C70B  (3055077131)
 *   e = 65537
 *   d = 2404741409  (SECRET — not here!)
*/

/* Modulus n (big-endian byte array, RSA_SIG_SIZE bytes) */
/* 0xB618C70B -> {0xB6, 0x18, 0xC7, 0x0B} */
static const uint8_t rsa_public_n[RSA_SIG_SIZE] = {
    0xB6, 0x18, 0xC7, 0x0B
};

/* Public exponent e (stored as uint32_t; e=65537 is standard) */
#define RSA_PUBLIC_E            (65537UL)

/*
 * RSA signature is at the END of the payload, after the firmware binary.
 *
 * Flash layout (at QSPI_BASE_ADDR = 0x90000000):
 *   [0x00]              Firmware binary (fw_size bytes) — vector table at 0x00
 *   [0x00+fw_size]      RSA signature (RSA_SIG_SIZE bytes)
 *   [0x00+fw_size+sig]  fw_size footer (4 bytes, little-endian)
 *   [0x00+fw_size+sig+4] Magic marker 0x55667788 (4 bytes)
 *   [...]               0xFF (erased flash)
 *
 * The header (12 bytes) is NOT stored in flash — only used during UART transfer.
 * On boot, binary search finds the data/0xFF boundary, verifies the magic marker
 * 0x55667788, then reads fw_size from the 4 bytes before the marker.
 *
 * Prerequisite: flash MUST be fully erased (0xFF) before writing payload.
 */

/* Size of the fw_size footer (appended after the signature) */
#define FW_SIZE_FOOTER_SIZE     (4U)

/* Magic marker appended after fw_size footer to mark end of payload */
/* Chosen as 0x55667788 — unlikely to appear in firmware binary          */
#define PAYLOAD_END_MARKER      (0x55667788UL)
#define PAYLOAD_END_MARKER_SIZE (4U)


typedef struct
{
    uint32_t size;
    uint32_t crc32;
} FirmwareInfo;

// UART
void Bootloader_SendErrorCmd(const char *msg, uint8_t error_code);
void UART_SendString(UART_HandleTypeDef *huart, const char *str);
void UART_SendLine(UART_HandleTypeDef *huart, const char *str);

/* Bootloader update firmware */
int8_t Bootloader_UpdateFirmware(void);

/* RSA signature verification (called before jumping to application) */
int8_t Bootloader_VerifyRSASignature(void);

/* Jump to application in QSPI */
void Bootloader_JumpToApplication(void);

#endif /* INC_BOOTLOADER_H_ */
